---
- name: Config Deployer, Install nginx, ruby, mongoDB
  hosts: webservers
  sudo: True
  roles:
    - ansible-role-repo-epel
    - ansible-role-security
    - ansible-role-git
    - ansible-role-nginx
    - ansible-role-nodejs
    - ruby
    - mysql
    - suishouji
